### ISSUE TITLE
Can't run examples/test-suite-committers.pl in latest repository.

### ISSUE THREAD

**Issue by Xliff** [moritz/svg-plot#10]
It turns out that the data structure generated by SVG::Plot::Pie had extra array levels in it.

The included patch seems to get things working properly and the result is viewable in Chromium.
If a PR is preferred, please let me know.

[pie-patch.txt](https://github.com/moritz/svg-plot/files/428791/pie-patch.txt)

**Comment by moritz** [comment]
Thanks @Xliff.

A PR would indeed be preferable, or you can accept my invitation to this repo and push it directly.

Cheers,
Moritz
