### ISSUE TITLE
LTA bug when installing SVG::Plot

### ISSUE THREAD

**Issue by cschwenz** [moritz/svg-plot#6]
==> Fetching SVG::Plot
    ==> Building SVG::Plot
    Compiling lib/SVG/Box.pm to mbc
    Use of Nil in numeric context  in block  at lib/Panda/Builder.pm:125
    Compiling lib/SVG/Plot.pm to mbc

On Mac OS 10.10.4 the install of SVG::Plot consistently hangs when compiling to mbc.  :-(
`^C`-ing the hung process and restarting the install usually gets SVG::Plot to successfully install.

I labeled this as an LTA bug because SVG::Plot is referenced by the Task::Star bundle.

**Comment by moritz** [comment]
The warning comes out of Panda::Builder, so I'd assume this is a bug in Panda::Builder, not SVG::Plot, unless you can point to something in SVG::Box that shouldn't be there that trips up Panda::Builder

**Comment by cschwenz** [comment]
Sorry, I'll remove the extraneous info:

    Compiling lib/SVG/Plot.pm to mbc

***On Mac OS 10.10.4 the install of SVG::Plot consistently hangs when compiling to mbc. :-(***

`^C`-ing the hung process and restarting the install *usually* (but not always) gets SVG::Plot to successfully install.

I labeled this as an LTA bug because SVG::Plot is referenced by the Task::Star bundle.
